export const skills = [
"Semantic & accesiable HTML",
"Error handling",
"Git",
"Responsive Web Design",
"React",
"GitHub Pull Request & Review",
//eslint-disable-next-line no-script-url
"JavaScript: ES6+",
"React Hooks",
"NPM",
"Working with API (fetch, axios)",
"Redux (Toolkit)",
"Immutability",
"Promises, Async/Await",
"Redeux-Saga",
"Markdown",
"Debugging",
"React Router",
"Scrum",
"CSS Flexbox",
"CSS Grid",
"Trello",
"Teamwork",
"CSS BEM convencion",
];

export const nextSkills = [
    "JS classes",
    "Unit Testing",
    "Node.js",
    "TypeScript",
    "Cypress",
    "React Context",
];